/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as RecipesImportRouteImport } from './routes/recipes/import'
import { Route as RecipesDigestRouteImport } from './routes/recipes/digest'
import { Route as RecipesCreateRouteImport } from './routes/recipes/create'
import { Route as RecipesIdRouteImport } from './routes/recipes/$id'
import { Route as RecipesIdCookCookIdRouteImport } from './routes/recipes/$id_.cook.$cookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesImportRoute = RecipesImportRouteImport.update({
  id: '/recipes/import',
  path: '/recipes/import',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesDigestRoute = RecipesDigestRouteImport.update({
  id: '/recipes/digest',
  path: '/recipes/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesCreateRoute = RecipesCreateRouteImport.update({
  id: '/recipes/create',
  path: '/recipes/create',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdCookCookIdRoute = RecipesIdCookCookIdRouteImport.update({
  id: '/recipes/$id_/cook/$cookId',
  path: '/recipes/$id/cook/$cookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes/create': typeof RecipesCreateRoute
  '/recipes/digest': typeof RecipesDigestRoute
  '/recipes/import': typeof RecipesImportRoute
  '/recipes': typeof RecipesIndexRoute
  '/recipes/$id/cook/$cookId': typeof RecipesIdCookCookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes/create': typeof RecipesCreateRoute
  '/recipes/digest': typeof RecipesDigestRoute
  '/recipes/import': typeof RecipesImportRoute
  '/recipes': typeof RecipesIndexRoute
  '/recipes/$id/cook/$cookId': typeof RecipesIdCookCookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes/create': typeof RecipesCreateRoute
  '/recipes/digest': typeof RecipesDigestRoute
  '/recipes/import': typeof RecipesImportRoute
  '/recipes/': typeof RecipesIndexRoute
  '/recipes/$id_/cook/$cookId': typeof RecipesIdCookCookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recipes/$id'
    | '/recipes/create'
    | '/recipes/digest'
    | '/recipes/import'
    | '/recipes'
    | '/recipes/$id/cook/$cookId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recipes/$id'
    | '/recipes/create'
    | '/recipes/digest'
    | '/recipes/import'
    | '/recipes'
    | '/recipes/$id/cook/$cookId'
  id:
    | '__root__'
    | '/'
    | '/recipes/$id'
    | '/recipes/create'
    | '/recipes/digest'
    | '/recipes/import'
    | '/recipes/'
    | '/recipes/$id_/cook/$cookId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipesIdRoute: typeof RecipesIdRoute
  RecipesCreateRoute: typeof RecipesCreateRoute
  RecipesDigestRoute: typeof RecipesDigestRoute
  RecipesImportRoute: typeof RecipesImportRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  RecipesIdCookCookIdRoute: typeof RecipesIdCookCookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/import': {
      id: '/recipes/import'
      path: '/recipes/import'
      fullPath: '/recipes/import'
      preLoaderRoute: typeof RecipesImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/digest': {
      id: '/recipes/digest'
      path: '/recipes/digest'
      fullPath: '/recipes/digest'
      preLoaderRoute: typeof RecipesDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/create': {
      id: '/recipes/create'
      path: '/recipes/create'
      fullPath: '/recipes/create'
      preLoaderRoute: typeof RecipesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id_/cook/$cookId': {
      id: '/recipes/$id_/cook/$cookId'
      path: '/recipes/$id/cook/$cookId'
      fullPath: '/recipes/$id/cook/$cookId'
      preLoaderRoute: typeof RecipesIdCookCookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipesIdRoute: RecipesIdRoute,
  RecipesCreateRoute: RecipesCreateRoute,
  RecipesDigestRoute: RecipesDigestRoute,
  RecipesImportRoute: RecipesImportRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  RecipesIdCookCookIdRoute: RecipesIdCookCookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
