/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as RecipesStealRouteImport } from './routes/recipes/steal'
import { Route as RecipesDigestRouteImport } from './routes/recipes/digest'
import { Route as RecipesCreateRouteImport } from './routes/recipes/create'
import { Route as RecipesIdRouteImport } from './routes/recipes/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesStealRoute = RecipesStealRouteImport.update({
  id: '/recipes/steal',
  path: '/recipes/steal',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesDigestRoute = RecipesDigestRouteImport.update({
  id: '/recipes/digest',
  path: '/recipes/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesCreateRoute = RecipesCreateRouteImport.update({
  id: '/recipes/create',
  path: '/recipes/create',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes/create': typeof RecipesCreateRoute
  '/recipes/digest': typeof RecipesDigestRoute
  '/recipes/steal': typeof RecipesStealRoute
  '/recipes': typeof RecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes/create': typeof RecipesCreateRoute
  '/recipes/digest': typeof RecipesDigestRoute
  '/recipes/steal': typeof RecipesStealRoute
  '/recipes': typeof RecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/recipes/create': typeof RecipesCreateRoute
  '/recipes/digest': typeof RecipesDigestRoute
  '/recipes/steal': typeof RecipesStealRoute
  '/recipes/': typeof RecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recipes/$id'
    | '/recipes/create'
    | '/recipes/digest'
    | '/recipes/steal'
    | '/recipes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recipes/$id'
    | '/recipes/create'
    | '/recipes/digest'
    | '/recipes/steal'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/recipes/$id'
    | '/recipes/create'
    | '/recipes/digest'
    | '/recipes/steal'
    | '/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipesIdRoute: typeof RecipesIdRoute
  RecipesCreateRoute: typeof RecipesCreateRoute
  RecipesDigestRoute: typeof RecipesDigestRoute
  RecipesStealRoute: typeof RecipesStealRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/steal': {
      id: '/recipes/steal'
      path: '/recipes/steal'
      fullPath: '/recipes/steal'
      preLoaderRoute: typeof RecipesStealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/digest': {
      id: '/recipes/digest'
      path: '/recipes/digest'
      fullPath: '/recipes/digest'
      preLoaderRoute: typeof RecipesDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/create': {
      id: '/recipes/create'
      path: '/recipes/create'
      fullPath: '/recipes/create'
      preLoaderRoute: typeof RecipesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipesIdRoute: RecipesIdRoute,
  RecipesCreateRoute: RecipesCreateRoute,
  RecipesDigestRoute: RecipesDigestRoute,
  RecipesStealRoute: RecipesStealRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
